// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: esp32

#include "ui/ui.h"

#include "ui_manager/animation.h"
#include "ui_manager/pm.h"

#include "view.h"

extern uint32_t startup_animation_time;

const char * TAG = "ui_events";

char buf1[16];
char buf2[16];
lv_timer_t *g_timer = NULL;
static uint8_t tomato_seconds;
static uint8_t tomato_minutes;
static bool tomato_status = 0;

void my_timer(lv_timer_t *timer)
{
	tomato_seconds ++;
	if(tomato_seconds == 60){
		tomato_minutes ++;
		tomato_seconds = 0;
	}
	ESP_LOGI("ui_event", "my_timer called with user data");
	if(tomato_seconds<10)
	{
		lv_snprintf(buf2, sizeof(buf2), "0%d", tomato_seconds);
	}else{
		lv_snprintf(buf2, sizeof(buf2), "%d", tomato_seconds);
	}
	if(tomato_minutes<10)
	{
		lv_snprintf(buf1, sizeof(buf1), "0%d", tomato_minutes);
	}else{
		lv_snprintf(buf1, sizeof(buf1), "%d", tomato_minutes);
	}
	lv_label_set_text(ui_TimerMin, buf1);
	lv_label_set_text(ui_TimerSec, buf2);
	lv_arc_set_value(ui_TimerArc, tomato_seconds);
}

void create_timer(uint8_t timer_type)
{
	if (g_timer != NULL)
	{
		lv_timer_del(g_timer);
		g_timer = NULL;
	}
	if(timer_type)g_timer = lv_timer_create(my_timer, 1000, NULL);
}

void startup_cb(lv_event_t *e)
{
	startup_animation();

	// _ui_screen_change(&ui_Page_Home, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Page_Home_screen_init);
}

void homeloaded_cb(lv_event_t *e)
{
	ESP_LOGI(TAG, "homeloaded_cb");
	lv_group_remove_all_objs(g_main);
	lv_group_add_obj(g_main, ui_menutomato);
	lv_group_add_obj(g_main, ui_menurunning);
	lv_group_add_obj(g_main, ui_menudataviewer);
	lv_group_add_obj(g_main, ui_menusetting);
}

/***************************************** Menu ***************************************/
void menutomato_cb(lv_event_t * e)
{
	ESP_LOGI(TAG, "menutomato_cb");
	_ui_screen_change(&ui_Page_Counter, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Page_Counter_screen_init);
	lv_group_remove_all_objs(g_main);
	lv_group_add_obj(g_main, ui_TimerStartStop);
	lv_group_add_obj(g_main, ui_TimerAdd);
	lv_group_add_obj(g_main, ui_TimerReset);
	lv_group_add_obj(g_main, ui_TimerBackHome);
}
void menucounting_cb(lv_event_t * e)
{

}
void menudataviewer_cb(lv_event_t * e)
{

}
void menusetting_cb(lv_event_t * e)
{

}
/***************************************** Tomato ***************************************/
void tomoatoarc_cb(lv_event_t * e)
{
	ESP_LOGI(TAG, "tomoatoarc_cb");
}
void tomatobegin_cb(lv_event_t * e)
{
	ESP_LOGI(TAG, "tomatobegin_cb");
	if(!tomato_status)
	{
		tomato_status = 1;
		create_timer(1);
		lv_obj_set_style_bg_img_src(ui_TimerStartStop, &ui_img_tomato_stop_png, LV_PART_MAIN | LV_STATE_DEFAULT);
	}else
	{
		tomato_status = 0;
		create_timer(0);
		lv_obj_set_style_bg_img_src(ui_TimerStartStop, &ui_img_tomato_begin_png, LV_PART_MAIN | LV_STATE_DEFAULT);
	}
}
void tomatoadd_cb(lv_event_t * e)
{

}
void tomatoreset_cb(lv_event_t * e)
{
	ESP_LOGI("ui_event", "tomatoreset_cb");
	tomato_seconds = 0;
	tomato_minutes = 0;
	lv_label_set_text(ui_TimerMin, "00");
	lv_label_set_text(ui_TimerSec, "00");
}
void tomatoend_cb(lv_event_t * e)
{
	ESP_LOGI("ui_event", "tomatoend_cb");
	_ui_screen_change(&ui_Page_Home, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Page_Home_screen_init);
}

/***************************************** Tomato Selector ***************************************/
void Selectforward_cb(lv_event_t * e)
{

}
void Selectbackward_cb(lv_event_t * e)
{
	
}
/***************************************** DataViewer ***************************************/


/***************************************** Setting ***************************************/

